version: '3'

services:
  app:
    build: 
      context: node
    container_name: app
    tty: true
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    ports:
      - "3000:3000"

  db: 
    image: mysql:8.1
    container_name: db
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: non-root
      MYSQL_DATABASE: node-mysql
      MYSQL_PASSWORD: root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge